### ISSUE TITLE
Start using a logger throughout

### ISSUE THREAD

**Issue by jwodicka** [jwodicka/Mural-legacy#5]
Mural emits a lot of debug output to the console. This should be replaced with a sensible, configurable logging class - either something good that we can just pull in, or something simple we build ourselves.

**Comment by bishoprook** [comment]
I'm generally a fan of log4net: http://logging.apache.org/log4net/

It's configured in AppConfig and is fairly easy to work with.  Has multiple levels of logging built in, and quite a few "log appenders" that can go to files, Windows event log, etc.

**Comment by jwodicka** [comment]
This seems like a good idea to me. I'm also a log4j user elsewhere, so
staying "in-family" will be nice for my own comprehension.
